# docs/src/orchid/resources/config.yml
site:
  about:
    siteName: Library Loans Application
    siteDescription: The Library Loans Application is an basic Android application allowing users to view a certain list of books and loan them.
    siteAuthor: Manar Benkraouda - 3046175

Editorial:
  primaryColor: '#DE9149'
  social:
    github: 'manarbenkraouda/library-loans'
  metaComponents:
    - type: 'orchidSearch'
  menu:
    - type: 'separator'
      title: 'Wiki'
    - type: 'wiki'
    - type: 'page'
      itemId: 'Changelog'
    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'javadoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'javadoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'
  javadoc:
    sourceDirs:
      - './../../../../app/src/main/java'
  services:
    publications:
      stages:
        - type: 'githubPages'
          username: 'manarbenkraouda'
          repo: 'manarbenkraouda/library-loans'
  wiki:
    sections:
      userManual:
        adapter:
          type: "github"
          repo: "[manarbenkraouda/library-loans]"